INSERT INTO User (id, username, password) VALUES (1, 'shiva', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu');
INSERT INTO User (id, username, password) VALUES (2, 'balram', '$2a$04$PCIX2hYrve38M7eOcqAbCO9UqjYg7gfFNpKsinAxh99nms9e.8HwK');
INSERT INTO User (id, username, password) VALUES (3, 'varun', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu');


INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT) 
 VALUES('Team Lead','varun', 'Bench', 'EMP1052', 'NO');
 
INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT)  
VALUES('SSE','Shiva vadloori', 'Bench', 'EMP1044', 'NO');

INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT)  
VALUES('SSE','Balram', 'Bench', 'EMP1000', 'NO');

INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT)  
VALUES('SSE','Shiva Chander', 'Bench', 'EMP1049', 'NO');

INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT)  
VALUES('Senior Team Lead','Ranadheer', 'Bench', 'EMP100', 'YES');


INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (1,'JAVA');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (1,'SPRING');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (1,'SPRING BOOT');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (1,'HIBERNATE');

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,'JAVA');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,'SPRING');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,'SPRING SECURITY');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,'HIBERNATE');

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,'JAVA');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,'SPRING');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,'ANGULAR JS');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,'BACKBONE');

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (4,'JAVA');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (4,'SPRING');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (4,'SPRING SECURITY');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (4,'HIBERNATE');

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,'JAVA');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,'SPRING');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,'SPRING BOOT');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,'HIBERNATE');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,'ANGULAR JS');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,'BACKBONE');

