INSERT INTO User (id, username, password) VALUES (1, 'shiva', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu');
INSERT INTO User (id, username, password) VALUES (2, 'balram', '$2a$04$PCIX2hYrve38M7eOcqAbCO9UqjYg7gfFNpKsinAxh99nms9e.8HwK');
INSERT INTO User (id, username, password) VALUES (3, 'varun', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu');


INSERT INTO Employee(designation,employee_name)  VALUES('SSE','varun');
INSERT INTO Employee(designation,employee_name)  VALUES('SE','shiva v');
INSERT INTO Employee(designation,employee_name)  VALUES('SSE','balaram');
INSERT INTO Employee(designation,employee_name)  VALUES('SE','shiva chander');
INSERT INTO Employee(designation,employee_name)  VALUES('TL','Ranadheer');
INSERT INTO Employee(designation,employee_name)  VALUES('SE','Sai');


INSERT INTO SKILL(LEVEL,SKILL_NAME) VALUES (6,'JAVA');
INSERT INTO SKILL(LEVEL,SKILL_NAME) VALUES (7,'HADOOP');
INSERT INTO SKILL(LEVEL,SKILL_NAME) VALUES (8,'INFORMATICA');
INSERT INTO SKILL(LEVEL,SKILL_NAME) VALUES (9,'BIG_DATA');

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (1,1);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (1,2);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (1,3);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (1,4);


INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,1);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,2);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,3);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,4);

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,1);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,2);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,3);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,4);

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (4,1);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (4,2);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (4,3);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (4,4);

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,1);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,2);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,3);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,4);

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (6,1);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (6,2);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (6,3);
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (6,4);
