INSERT INTO User (id, username, password) VALUES (1, 'shiva', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu');
INSERT INTO User (id, username, password) VALUES (2, 'balram', '$2a$04$PCIX2hYrve38M7eOcqAbCO9UqjYg7gfFNpKsinAxh99nms9e.8HwK');
INSERT INTO User (id, username, password) VALUES (3, 'varun', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu');


INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT) 
 VALUES('Team Lead','varun', 'Bench', 'EMP1052', 'NO');
 
INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT)  
VALUES('SSE','Shiva vadloori', 'Khols', 'EMP1044', 'YES');

INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT)  
VALUES('SSE','Balram', 'Bench', 'EMP1000', 'NO');

INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT)  
VALUES('SSE','Shiva Chander', 'kHOLS', 'EMP1049', 'YES');

INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT)  
VALUES('Senior Team Lead','Ranadheer', 'Macys', 'EMP100', 'YES');

INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT)  
VALUES('Team Lead','Rana', 'Khols', 'EMP1001', 'YES');

INSERT INTO Employee(DESIGNATION,employee_name, PROJECT_NAME, REGISTERED_ID, IS_IN_PROJECT)  
VALUES('SSE','Ravi', 'Khols', 'EMP105', 'YES');


INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (1,'Java');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (1,'PE');


INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,'Java');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,'PE');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (2,'UI/UX');


INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,'Java');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,'UI/UX');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (3,'PE');


INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (4,'Java');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (4,'PE');


INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,'Java');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,'PE');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,'UI/UX');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (5,'QA');

INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (6,'Hadoop');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (6,'Big Data');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (6,'Data Science');


INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (7,'UI/UX');
INSERT INTO EMPLOYEE_SKILL (EMPLOYEE_ID,SKILL_ID) VALUES (7,'AEM');


